Repository CDS-Seminar-Team3/CDS3-Server, pull requests merged in 2023-05, with the labels that each got.

#1 [chore] 프로젝트세팅, entity 세팅
  build.gradle
  src/main/java/com/server/cds3/Cds3Application.java
  src/main/java/com/server/cds3/common/dto/ApiResponseDto.java
  src/main/java/com/server/cds3/common/exception/ControllerExceptionAdvice.java
  src/main/java/com/server/cds3/common/exception/ErrorStatus.java
  src/main/java/com/server/cds3/common/exception/SuccessStatus.java
  src/main/java/com/server/cds3/controller/UserController.java
  src/main/java/com/server/cds3/domain/AuditingTimeEntity.java
  src/main/java/com/server/cds3/domain/Petition.java
  src/main/java/com/server/cds3/domain/PetitionLink.java
  src/main/java/com/server/cds3/domain/PetitionMember.java
  src/main/java/com/server/cds3/domain/User.java
  src/main/java/com/server/cds3/dto/request/UserRequestDto.java
  src/main/java/com/server/cds3/dto/response/UserResponseDto.java
  src/main/java/com/server/cds3/repository/UserRepository.java
  src/main/java/com/server/cds3/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: chore

#3 rds fix
  src/main/resources/application.yaml
Labels: fix

#5 [feat] post agree petition
  build.gradle
  src/main/java/com/server/cds3/common/exception/SuccessStatus.java
  src/main/java/com/server/cds3/controller/PetitionDetailController.java
  src/main/java/com/server/cds3/dto/request/PostPetitionAgreeRequestDto.java
  src/main/java/com/server/cds3/dto/request/PostPetitionAgreeResponseDto.java
  src/main/java/com/server/cds3/repository/PetitionMemberRepository.java
  src/main/java/com/server/cds3/repository/PetitionRepository.java
  src/main/java/com/server/cds3/service/PetitionDetailService.java
Labels: feat

#8 [feat] get all my petition
  src/main/java/com/server/cds3/common/exception/SuccessStatus.java
  src/main/java/com/server/cds3/controller/MyPetitionController.java
  src/main/java/com/server/cds3/dto/response/myPetition/GetMyPetitionResponseDto.java
  src/main/java/com/server/cds3/repository/PetitionMemberRepository.java
  src/main/java/com/server/cds3/repository/PetitionRepository.java
  src/main/java/com/server/cds3/service/MyPetitionService.java
Labels: feat

#10 [feat] post petition
  src/main/java/com/server/cds3/Cds3Application.java
  src/main/java/com/server/cds3/controller/PetitionController.java
  src/main/java/com/server/cds3/domain/Petition.java
  src/main/java/com/server/cds3/dto/request/petition/PetitionRegisterRequestDto.java
  src/main/java/com/server/cds3/dto/response/petition/PetitionRegisterResponseDto.java
  src/main/java/com/server/cds3/service/PetitionService.java
Labels: feat

#12 [feat] get petition detail view
  src/main/java/com/server/cds3/common/exception/SuccessStatus.java
  src/main/java/com/server/cds3/controller/PetitionDetailController.java
  src/main/java/com/server/cds3/dto/response/petition/PetitionDetailResponseDto.java
  src/main/java/com/server/cds3/repository/PetitionMemberRepository.java
  src/main/java/com/server/cds3/service/PetitionDetailService.java
Labels: feat

#14 [feat] get petition agree list
  src/main/java/com/server/cds3/controller/PetitionAgreeListController.java
  src/main/java/com/server/cds3/dto/response/petition/PetitionAgreeListResponseDto.java
  src/main/java/com/server/cds3/repository/PetitionMemberRepository.java
  src/main/java/com/server/cds3/service/PetitionAgreeListService.java
Labels: feat

#15 [feat] get main page
  build.gradle
  src/main/java/com/server/cds3/common/exception/SuccessStatus.java
  src/main/java/com/server/cds3/config/QueryDslConfig.java
  src/main/java/com/server/cds3/controller/MainController.java
  src/main/java/com/server/cds3/dto/response/main/GetMainPetitionDto.java
  src/main/java/com/server/cds3/dto/response/main/IssuePetition.java
  src/main/java/com/server/cds3/dto/response/main/NewPetition.java
  src/main/java/com/server/cds3/repository/PetitionRepository.java
  src/main/java/com/server/cds3/repository/PetitionRepositoryCustom.java
  src/main/java/com/server/cds3/repository/PetitionRepositoryImpl.java
  src/main/java/com/server/cds3/service/MainService.java
Labels: feat

#18 [feat] cors error
  build.gradle
  src/main/java/com/server/cds3/config/SecurityConfig.java
Labels: feat

#20 #19 [fix] 동의하기 수정
  src/main/java/com/server/cds3/dto/response/myPetition/GetMyPetitionResponseDto.java
  src/main/java/com/server/cds3/repository/PetitionMemberRepository.java
  src/main/java/com/server/cds3/service/MainService.java
  src/main/java/com/server/cds3/service/MyPetitionService.java
  src/main/resources/application.yaml
Labels: fix
